services:
  sfd-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sfd_container
    ports:
      - "8000:8000"  # Порт для бэкенда
      - "3000:3000"  # Порт для фронтенда
    restart: unless-stopped
    volumes:
      - ./:/app  # Монтируем весь проект для синхронизации
      - git-update-logs:/app/git-update.log
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admuser:0000@localhost:5432/postgres
    # Добавляем команду для отладки (если simple-start.sh не работает)
    command: ["/bin/sh", "-c", "ls -l /app && ./simple-start.sh"]

  db:
    image: postgres:14
    container_name: sfd_db
    environment:
      - POSTGRES_USER=admuser
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d smart_factory_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  git-update-logs:
  postgres_data: