version: '3'

services:
  sfd-app:
    build: .
    container_name: sfd_container
    ports:
      - "8001:8000"  # Порт для бэкенда
      - "3001:3000"  # Порт для фронтенда
    restart: unless-stopped
    volumes:
      - git-update-logs:/app/git-update.log

volumes:
  git-update-logs:
